# Generated by Django 3.1.4 on 2020-12-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intra', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
