# Generated by Django 3.1.4 on 2020-12-15 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intra', '0005_auto_20201215_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='intructor',
            new_name='instructor',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='user',
        ),
        migrations.AddField(
            model_name='rdv',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
